# Generated by Django 3.1.5 on 2021-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
