# Generated by Django 3.1.5 on 2021-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontosturisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='Avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
