# Generated by Django 3.1.5 on 2021-01-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('core', '0006_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTuristicos',
            new_name='PontoTuristico',
        ),
    ]
